### ISSUE TITLE
Symlinks to inputs are incorrectly rejected

### ISSUE THREAD

**Issue by peterebden** [bazelbuild/remote-apis-sdks#270]
If you have an action like:
```
work/
├── in
│   └── input.txt
└── out
    └── link -> ../input.txt
```
on calling `ComputeOutputsToUpload` on `out` you get an error like `work/in/input.txt is not under work/out`. This is allowed by the API (it says that output symlinks "may be links to other output files, or input files, ...").

I've had a bit of a look at `tree.go` but so far haven't managed to fix it without making things worse. I'm pretty sure this is because of passing `absPath` instead of `execRoot` to `loadFiles`, but simply altering that and passing `path` instead of the empty string prefixes the outputs in an unexpected way.

**Comment by ola-rozenfeld** [comment]
Thank you for finding the bug! Is the execRoot in this example `work` or `work/out`?

**Comment by ola-rozenfeld** [comment]
I added a test case in #284 but have been unable to reproduce the problem. I suspect it is related to #283 : currently RBE assumes all output paths are exec-root relative and not work-dir relative, and that is how we use the SDK as well. Note that you ComputeOutputsToUpload also accepts the exec root as a parameter, not the working directory.

**Comment by peterebden** [comment]
I don't recall a lot of context here but think it's safe to assume this is no longer an issue. Thanks for the test case!
