### ISSUE TITLE
Remove deleted api `grpc.WithBalancerName`

### ISSUE THREAD

**Issue by easwars** [bazelbuild/remote-apis-sdks#412]
We (grpc-go team) noticed that the `grpc.WithBalancerName` API is being used in your repo. This was deprecated about 4 years ago and was deleted recently in https://github.com/grpc/grpc-go/pull/5232.

We would recommend that you replace `grpc.WithBalancerName` with the following two dial options:
- Specify the balancer name of your choice using a default service config:
`WithDefaultServiceConfig(fmt.Sprintf(`{"loadBalancingConfig": [{"%s":{}}]}`, balancer.Name))`
- Disable the service config specified by your resolver:
`grpc.WithDisableServiceConfig` 

Thanks

**Comment by ukai** [comment]
with grpc-go@v1.46.0, compile error with `undefined: grpc.WithBalancerName`

**Comment by easwars** [comment]
> with grpc-go@v1.46.0, compile error with `undefined: grpc.WithBalancerName`

Yes, that API has been removed.
