### ISSUE TITLE
ByteStream `resource_name` is incorrect if the instance name is empty

### ISSUE THREAD

**Issue by juergbi** [bazelbuild/remote-apis-sdks#489]
`remote_execution.proto` specifies for the ByteStream `resource_name` that

> If it [instance_name] is the empty path, the leading slash is omitted

The CAS download and upload code currently doesn't omit the slash, causing [incompatibility with buildbox-casd](https://gitlab.com/BuildGrid/buildbox/buildbox-casd/-/merge_requests/284) and maybe other servers.

```
go/pkg/cas/upload.go:           req.ResourceName = fmt.Sprintf("%s/uploads/%s/blobs/%s/%d", u.InstanceName, uuid.New(), digest.Hash, digest.SizeBytes)
go/pkg/casng/uploader.go:       return fmt.Sprintf("%s/uploads/%s/blobs/%s/%d", instanceName, uuid.New(), hash, size)
go/pkg/client/cas_download.go:  return fmt.Sprintf("%s/blobs/%s/%d", c.InstanceName, hash, sizeBytes)
go/pkg/client/cas_upload.go:    return fmt.Sprintf("%s/uploads/%s/blobs/%s/%d", c.InstanceName, uuid.New(), hash, sizeBytes)

```

**Comment by mrahs** [comment]
Thank you for reporting this bug.

For my reference, this is the relevant API spec: https://github.com/bazelbuild/remote-apis/blob/cb8058798964f0adf6dbab2f4c2176ae2d653447/build/bazel/remote/execution/v2/remote_execution.proto#L223

I'll submit a PR to fix this asap.

**Comment by mrahs** [comment]
I've just merged the fix. It would be great if you can confirm it works as expected.
