### ISSUE TITLE
Feature: additional HTTP headers for remote requests

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/remote-apis-sdks#599]
This is a feature request for something equivalent to Bazel's `--remote_header`. Something like:

```
--remote_header=x-engflow-resource-tag=cost_center=moonshot
```

When the SDK is configured with the flag above, outgoing HTTP requests would have the header `x-engflow-resource-tag` set to `cost_center=moonshot`.

Use case: EngFlow supports a few custom headers. `x-engflow-resource-tag` lets clients add tags to their requests for cost analysis. For example, this could be used to distinguish costs of two teams that share the service, or a new toolchain that might use more execution resources.

**Comment by mrahs** [comment]
Sounds like a reasonable feature, but to be honest, we never needed it. I'd be happy to review a PR though.
