### ISSUE TITLE
Standalone tool for CAS Interaction

### ISSUE THREAD

**Issue by edbaunton** [bazelbuild/remote-apis-sdks#89]
The `rexec` tool is a great one stop shop for submitting and executing jobs synchronously.

We have a use case where we would like to get results directly from the ActionCache/CAS given only an ActionId (without the original input root, so we cannot submit the job again).

Would you be open to an additional command line tool dedicated to CAS interaction? Specifically, it would support upload/download of blobs and trees. Additionally, it would be able to interact with the ActionCache and check/download results.

We would be happy to contribute it!

**Comment by ola-rozenfeld** [comment]
Sorry, just saw this -- note that a command line tool for all of that already exists in https://github.com/bazelbuild/tools_remote/! It is in our plans to refactor that repo to use this one; while I'm sure it is helpful to have the SDK in multiple languages, I'm not so sure it is similarly helpful to have all the command line tools in all languages.
And even if it is helpful to have a separate Go tool mirroring tools_remote, then it's still a question of whether it should live here or in the tools_remote repository.

But yes, if tools_remote is not enough for your current use-case, and you send me a patch to add the tool, I'll be happy to review, and we can discuss then where it should live. WDYT?

**Comment by edbaunton** [comment]
Thanks @ola-rozenfeld! I missed your update and was not aware of `tools_remote`. We have a suite of tools available in C++ for CAS interaction now at [buildbox-tools](https://gitlab.com/BuildGrid/buildbox/buildbox-tools).

**Comment by ola-rozenfeld** [comment]
Note we now have a tool for this here as well -- check out go/cmd/remotetool (allows showing/downloading action results, blobs and directories).
